services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token
        - github_actor
    container_name: "printscript-api"
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: printscript-db
      DB_PORT: 5432
      EXAMPLE_RUNTIME_ENV_VAR: "example runtime env var"
    env_file: ".env"
    depends_on:
      - db
      - redis

  db:
    container_name: "printscript-db"
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"

secrets:
  github_token:
    external: true
  github_actor:
    external: true