services:
  api:
    container_name: "printscript-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8086:8080
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    env_file: ".env"
    depends_on:
      - db
      - redis

  db:
    container_name: "printscript-db"
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"