name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew



      - name: Check secrets
        run: echo "USERNAME_PRINTSCRIPT is ${{ secrets.USERNAME_PRINTSCRIPT }}"
        env:
            USERNAME_PRINTSCRIPT: ${{ secrets.USERNAME_PRINTSCRIPT }}
            GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew build
        env:
          USERNAME_PRINTSCRIPT: ${{secrets.USERNAME_PRINTSCRIPT }}
          GIT_TOKEN: ${{secrets.GIT_TOKEN }}
